name: Workflow for Docker using Snyk 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: vulnerables/web-dvwa
        args: --json-file-output=vuln.json --severity-threshold=high

    - name: Upload Snyk scan results
      uses: actions/upload-artifact@v4
      with:
        name: snyk-results
        path: output/vuln.json
